import * as XLSX from "xlsx";

export function handleDownloadTemplate() {
    const headers = [
        [
          "NumeroPoliza",
          "IDMascota",
          "NombreMascota",
          "Raza",
          "FechaNacimientoMascotaEstimada",
          "EdadIngresoMascota",
          "EdadActualMascota",
          "SexoMascota",
          "Producto",
          "Plan",
          "Estado",
          "InicioVigencia",
          "FinVigencia",
          "BolsaAseguradaServiciosVeterinarios",
          "SaldoGastosVeterinarios",
          "IncluyeRc",
          "BolsaAseguradaRC",
          "SaldoRC",
          "TipoIDAsegurado",
          "NumeroIDAsegurado",
          "AseguradoNombreCompleto",
          "AseguradoPrimerApellido",
          "AseguradoSegundoApellido",
          "AseguradoSexo",
          "Telefono",
          "Email",
          "Direccion",
          "Ciudad",
          "TipoIDAseguradoSecundario",
          "NumeroIDAseguradoSecundario",
          "AseguradoSecundarioNombreCompleto",
          "AseguradoSecundarioPrimerApellido",
          "AseguradoSecundarioSegundoApellido",
          "AseguradoSecundarioSexo",
          "Telefono2",
          "Email3",
          "Direccion4",
          "Ciudad5",
          "FormaDePago",
          "Ultimos4DigitosCuenta",
          "Banco",
          "AutorizaDebitoAutomatico",
          "TipoCuenta",
          "Franquicia",
          "CodigoOficina",
          "CodigoAsesor",
          "ApuntadorDebitoAutomatico",
          "PrimaMensualSinIVA",
          "PrimaAnualSinIVA",
          "PrimaMensualConIVA",
          "PrimaAnualConIVA",
          "TerminacionCarencia",
          "Dia15PostVigencia",
          "Dia25PostVigencia",
          "Dia30PostVigencia",
          "NumeroMicrochipMascota",
          "ViaDePago",
          "TipoPoliza",
          "EmpresaColectiva",
          "CargoColectiva",
          "FechaCancelacion",
          "MotivoCancelacion",
          "NombreAsesor",
          "TrasladoOtraPoliza",
          "SedeEmpresaColectiva",
          "Modificaciones",
          "FechaExpedicionPoliza",
          "FechaUltimoRecibo",
        ]
      ];

    const workbook = XLSX.utils.book_new();
    const worksheet = XLSX.utils.aoa_to_sheet(headers);
    XLSX.utils.book_append_sheet(workbook, worksheet, "Plantilla");
    XLSX.writeFile(workbook, "plantilla.xlsx");
}